### ISSUE TITLE
Crash when searching the contact and tapped Cancel

### ISSUE THREAD

**Issue by djaygit** [ipraba/EPContactsPicker#14]

**Comment by francisadelante** [comment]
yes it crashed!

**Comment by antons81** [comment]
bug confirmed.

**Comment by antons81** [comment]
if let contactsForSection = orderedContacts[sortedContactKeys[indexPath.section]] {
                contact = EPContact(contact: contactsForSection[indexPath.row]) // crash is here
            }
For example I have 6 contacts, but 2 of them in 1 section. When tap on cancel on search bar it recognizing as 5 contacts and crashing with error out of index

**Comment by roro95** [comment]
I changede in EPContactPicker
   public func searchBarCancelButtonClicked(searchBar: UISearchBar) {
        searchBar.text = ""
        dispatch_async(dispatch_get_main_queue(), {
            //self.tableView.reloadData()
            self.reloadContacts()
        })
    }

**Comment by antons81** [comment]
I tried it it's still crash

**Comment by ray1021** [comment]
I mark the line on func searchBarCancelButtonClicked
// searchBar.text = "" 
it would not crash.

**Comment by ray1021** [comment]
Because searchBar.text = "" will trigger func updateSearchResultsForSearchController ,
and it  will call self.tableView.reloadData() , then trigger numberOfSectionsInTableView ,
in this case, resultSearchController.active is true , so section always return 1.
