### ISSUE TITLE
Installation/Initialization Issue

### ISSUE THREAD

**Issue by phage04** [ipraba/EPContactsPicker#15]
Xcode 7.3 pod installation working but EPContactsPicker can't be detected. 

<img width="1049" alt="screen shot 2016-04-22 at 1 21 11 am" src="https://cloud.githubusercontent.com/assets/12881926/14718329/a460f240-0828-11e6-8a52-4bbdc6e6a687.png">

**Comment by ipraba** [comment]
Check by building it at-least once after pod install/pod update
