### ISSUE TITLE
Multi Selection

### ISSUE THREAD

**Issue by MVakas** [ipraba/EPContactsPicker#2]
Multi selection doesn’t work properly. The tick marks on the cells doesn’t show up properly. For example if you select two contacts in multiselection, the tick marks are displayed on the other cells as well.

**Comment by ipraba** [comment]
Now fixed in this commit  (https://github.com/ipraba/EPContactsPicker/commit/e3eaf7b1b4b4eeef8ccf9b7ae5a279dddd13e799) 

Kindly make use of it.
