### ISSUE TITLE
I need this code for Objective C

### ISSUE THREAD

**Issue by parthpatel1105** [ipraba/EPContactsPicker#20]
I need this code for Objective C

**Comment by ipraba** [comment]
If you want to use the control in objective-c project you can use pod to install and directly import like

`#import <EPContactsPicker/EPContactsPicker-Swift.h>`

In your code presentation
`
EPContactsPicker *picker = [[EPContactsPicker alloc] initWithDelegate:self multiSelection:YES];
    [self presentViewController:picker animated:YES completion:nil];
`

Hope this helps

**Comment by inPhilly** [comment]
Is there any way to get this as a Carthage framework for objective-c? It's so good, but I haven't moved into the modern age yet with Swift, which has made CocoaPods difficult to use, so I use Carthage. I would love to be able to use this code. It is awesome.

**Comment by jeyremy** [comment]
Hi, i'm interested too, but xcode keep telling me  for : 
[[EPContactsPicker alloc] initWithDelegate:self multiSelection:YES];
no visible @interface for  EPContactsPicker initWithDelegate:multiSelection:
