### ISSUE TITLE
Bundle resources aren't available when installed via CocoaPods

### ISSUE THREAD

**Issue by wryphonedev** [ipraba/EPContactsPicker#21]
2016-06-30 10:55:17.239 RecCheck[14128:3479311] *** Terminating app due to uncaught exception 'NSInternalInconsistencyException', reason: 'Could not load NIB in bundle: '...A611DD64B6C2/MyApp.app> (loaded)' with name 'EPContactCell''

Please update the podspec to expose the bundle, then update the EPContactsPicker class to load the bundle with the specified key. For more information: [https://the-nerd.be/2015/08/07/load-assets-from-bundle-resources-in-cocoapods/](url)

**Comment by wryphonedev** [comment]
PR #22 resolves this issue.

**Comment by grahammccarthy** [comment]
I am experiencing this issue as well.  @ipraba  can you review PR #22  and merge it in if you are happy with it. It looks good to me.

**Comment by ipraba** [comment]
I merged it https://github.com/ipraba/EPContactsPicker/pull/22 and updated the pods version to 1.0.6.
