### ISSUE TITLE
trying to send data from ViewController to EPcontactsPicker file.

### ISSUE THREAD

**Issue by davidparra11** [ipraba/EPContactsPicker#23]
i had been trying for many ways send data on a variable from any ViewController to EPContactPicker file, but it´s been imposible.
thank a lot for any suppport

**Comment by ipraba** [comment]
You may try to inherit EPContactsPicker and pass on your data to that and manipulate your logic in the inherited view controller.

**Comment by davidparra11** [comment]
okey friend, I will try to do this, thank so much for you attention and answer.
