### ISSUE TITLE
Ability to show only contacts with email or phone number

### ISSUE THREAD

**Issue by vikmeup** [ipraba/EPContactsPicker#3]

**Comment by ipraba** [comment]
It would be really helpful if you can please provide more info on your issue. I will try to solve it.

**Comment by vikmeup** [comment]
`CNContactPickerViewController` has property `predicateForSelectionOfProperty = NSPredicate(format: "emailAddresses.@count >= 1", argumentArray: nil)` that allow you to show only contacts that has at least one email, or one phone number, or person that has a name. 
It would be great if you can implement this feature.

**Comment by ipraba** [comment]
thanks a lot for reviewing my component and giving me the feedback. I will add this in my todo list.

**Comment by garnett** [comment]
@ipraba one suggestion here: IMHO it is good idea to "modernize/swiftize" this API and use actual callback instead of stringy predicate

**Comment by andreichirkunovgoon** [comment]
I would be very thankful if there would be this possibility to only show contacts with a phone number
