### ISSUE TITLE
The word "Optional" appears before every contact name

### ISSUE THREAD

**Issue by roblav96** [ipraba/EPContactsPicker#31]
## Example
![example](http://i.imgur.com/Zb0Bmsx.jpg)
http://i.imgur.com/Zb0Bmsx.jpg

## Podfile
```ruby
pod 'EPContactsPicker', :git => 'https://github.com/ipraba/EPContactsPicker'
use_frameworks!
```

**Comment by Sorix** [comment]
I can't reproduce that bug at my environment but I think #32 will fix it, I will be very pleased if you can test it and report your results?

```ruby
pod 'EPContactsPicker', :git => 'https://github.com/Sorix/EPContactsPicker', :branch => 'fix/31'
```

**Comment by roblav96** [comment]
Running the `Contacts Picker` demo you've supplied this issue does not occur. 

I've been installing my pod from the latest `2.0.0` and using `use_frameworks!` Let me try this PR and see if it helps.

**Comment by Sorix** [comment]
Demo I've supplied is equal to my pull request :)

**Comment by roblav96** [comment]
@Sorix It's working properly on the demo so no issues there.

My only concern is the migration to Swift 3 as you've dropped the `obj-c` bridging support.
### [From 1.0.6](https://github.com/ipraba/EPContactsPicker/blob/1.0.6/Pods/EPContactsPicker.swift)
```swift
@objc public protocol EPPickerDelegate { // NOTICE THE @objc
    optional    func epContactPicker(_: EPContactsPicker, didContactFetchFailed error: NSError)
    optional    func epContactPicker(_: EPContactsPicker, didCancel error: NSError)
    optional    func epContactPicker(_: EPContactsPicker, didSelectContact contact: EPContact)
    optional    func epContactPicker(_: EPContactsPicker, didSelectMultipleContacts contacts: [EPContact])
}
```
### [To 2.0.0](https://github.com/ipraba/EPContactsPicker/blob/2.0.0/Pods/EPContactsPicker.swift)
```swift
public protocol EPPickerDelegate { // NOTICE THE MISSING @objc
    optional    func epContactPicker(_: EPContactsPicker, didContactFetchFailed error: NSError)
    optional    func epContactPicker(_: EPContactsPicker, didCancel error: NSError)
    optional    func epContactPicker(_: EPContactsPicker, didSelectContact contact: EPContact)
    optional    func epContactPicker(_: EPContactsPicker, didSelectMultipleContacts contacts: [EPContact])
}
```

Do you have plans to add an `Objective-C Bridging Header` file to support legacy users?
[BuildingCocoaApps/MixandMatch](https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html)
