### ISSUE TITLE
addSubView() not works expectedly

### ISSUE THREAD

**Issue by santanu4ver** [ipraba/EPContactsPicker#8]
Instead of using in an UINavigationController I tried to add it's view to an UIViewController class:

```
let contactScene = EPContactsPicker(delegate: self, multiSelection: true, subtitleCellType: SubtitleCellValue.Phonenumer)
self.view.addSubview(contactScene.view)
```

This shown up the EPContactsPicker effectively but when tap on any entry, the entries disappears leaving only grid lines. Am I supposed to add EPContactsPicker in above way, or what I need to do differently?

**Comment by ipraba** [comment]
@santanu4ver I intended to create this component as viewcontroller. Will checkout your scenario and will update soon

**Comment by santanu4ver** [comment]
Thanks. Appreciate your effort. This API is very good looking.
